### ISSUE TITLE
/back command will send player to unwanted place

### ISSUE THREAD

**Issue by JinOuYongGu** [WiIIiam278/HuskHomes2#120]
Version: HuskHomes v2.10

When I test the /back function on my server, I found that I won't teleport to the place death before.
Sometime I was teleport to the spawn of the world or recent places.

Even I set myself as an OP, the problem occured too.

**Comment by WiIIiam278** [comment]
@JinOuYongGu Can you confirm that you have granted the `huskhomes.back.death` permission node? /back will not work to your death position unless your permission nodes are set correctly.

**Comment by JinOuYongGu** [comment]
Yes, I have read the permission list and added it to my permission group.
My server runs Paper 1.16.5 and Waterfall

**Comment by WiIIiam278** [comment]
Are you able to specify steps to reproduce / video of this occurring? `/back` has been extensively tested.
Are you sure that all players have the `huskhomes.back.death` and `huskhomes.back` permission nodes when players die - and that you don't have any other plugins that supply a `/back` command? To double check, try doing `/huskhomes:back` instead of just `/back`.

**Comment by JinOuYongGu** [comment]
I found the reason: I set the gamerule **doImmediateRespawn** from true(default) to false
After I set it back to true, all things work smoothly!

**Comment by WiIIiam278** [comment]
Oh, OK, that's a little weird. All good, then.
