### ISSUE TITLE
Cross-server player respawn location synchronisation

### ISSUE THREAD

**Issue by justaureus** [WiIIiam278/HuskHomes2#123]
Add syncing of the player's bed and/or nether anchors to HuskSync.  This way, if a player dies on a server different from their bed location, they will be transferred to the proper location on the proper server.

If no bed/anchor is found, teleport the player to the designated spawn server/location.

**Comment by WiIIiam278** [comment]
Upon re-evaluation, while this meets the scope of HuskSync more closely in terms of being a synchronization feature, in terms of practical utility and implementation style I think an implementation in HuskHomes would make more sense and fit the needs of HuskHomes users more (who are already enjoying the enhancements of /back).

This would be a feature only for users on BungeeCord mode. Here's the plan:
* Add a new column in SQL (foreign key associated with a teleportation location) storing the SERVER ID of a player's respawn point
* Add another column in SQL (boolean) storing if they are currently respawning
* Add new listener class for detecting bed / nether thingy spawn updating
  * When detected, update column in SQL with the server id the player is on
* On the player respawn event, send the player to the server and set the is respawning flag in SQL
* When they arrive, detect if that flag is set. If so, teleport them to their respawn point as defined on the server! If said respawn point does not match that of a bed / respawn anchor (i.e. the respawn point has been unset/broken) then teleport the user to the cross server spawn point (if set; otherwise just take 'em to the world spawn on the server they are on).

While not the most elegant solution possible, I think it's fairly reasonable. HuskHomes is designed to work smoothly with or without BungeeCord (Only <15% of servers use Bungee features as per [stats](https://bstats.org/plugin/bukkit/HuskHomes/8430)) and while an alternative solution could be developed now requiring a bungee plugin, the work required in terms of multi modularising the plugin, adding the bungee plugin requirement, etc is unattractive compared to the gain of removing SQL queries. Especially because this is a pretty niche request.

PRs are welcome.

**Comment by WiIIiam278** [comment]
Planned for v3 (see #152)
