### ISSUE TITLE
rtp will cause lag

### ISSUE THREAD

**Issue by JinOuYongGu** [WiIIiam278/HuskHomes2#171]
when I test the /rtp command of huskhomes, I found that the MSPT of my server increased significantly (5 -> 15).
And if I keep repeating execute the rtp command, the MSPT will increase to 50+ when the server only 1 player online

**Comment by WiIIiam278** [comment]
This is expected as generating new chunks just does cause lag. That's why there's the cool-down feature in place.
Are you using paper or plain spigot? If you're using Spigot, switch to Paper as HuskHomes makes use of PaperLib to help alleviate this by asynchronously loading chunks before teleporting (though this does not eliminate this)
