### ISSUE TITLE
Warps don't TAB complete when permission restriction is enabled and the user has the `huskhomes.command.setwarp` node

### ISSUE THREAD

**Issue by ApliNi** [WiIIiam278/HuskHomes2#273]
Players have `huskhomes.command.warp, huskhomes.command.warp.*` privileges, The completion list is not displayed after typing `/warp `.

It can be used normally in the console. The previous version did not have this error.

**Comment by WiIIiam278** [comment]
I'm assuming you're using permission-restricted warps. `huskhomes.command.warp.*` is not a valid permission node. You must grant the nodes for each and every warp you wish to grant. Note though that permissions for `huskhomes.command.setwarp` does work as a bypass -- so the bug here is that the setwarp node does not apply to the filtering of TAB completion here.
