### ISSUE TITLE
Velocity Support

### ISSUE THREAD

**Issue by tommasobenatti** [WiIIiam278/HuskHomes2#38]
It would be cool to have support for the Velocity Proxy
Is it possible?

**Comment by iVillager** [comment]
Non è un plugin BungeeCord

**Comment by tommasobenatti** [comment]
![image](https://user-images.githubusercontent.com/62927722/120228692-ef6a7800-c24b-11eb-98a9-b49cc3f9ff43.png)
there are imports of bungeecord classes, are you sure that it will work under Velocity?

**Comment by WiIIiam278** [comment]
The plugin is a Spigot plugin. Currently I don't think it would work on Velocity since it utilities the BungeeCord Plugin Messaging channel. From my brief research, though, it seems like Velocity either provides this as well or has a similar implementation. Velocity support, therefore, is not off the cards. It needs testing however - @tommasobenatti  could you try running HuskHomes on a Velocity server for me with Bungee Mode enabled and seeing if it works?

**Comment by tommasobenatti** [comment]
I didn't tested, but if the plugin uses the bungeecord plugin messaging it will work just fine

**Comment by WiIIiam278** [comment]
> I didn't tested, but if the plugin uses the bungeecord plugin messaging it will work just fine

It does. In that case I'm closing this for now. Reopen if this isn't possible.
