### ISSUE TITLE
It can't migrate essentialsX date and cant use Tab to completion command

### ISSUE THREAD

**Issue by SnivyJ** [WiIIiam278/HuskHomes2#70]
JAVA : JDK-16.0.1
MC_VERSION : 3162-Spigot-f773da8-b121d3b (MC: 1.17)
ESSENTIALS_VERSION : EssentialsX-2.19.0-dev+221-1556b91
HuskHomes_VERSION : HuskHomes 2.6.3

Server:OnlineMoed=false
OtherPluginsList : CoreProtect, SimpleProtect, LuckPerms, TagSomeone, PlaceholderAPI, ColorSource, spark, AntiCreep, WallJump, ChestSort, ProtocolLib, ChopTree2, Void2Spawn, Tweakin, Multikills, sleep-most, Not-Too-Expensive, Yum, EntitySearch, LangUtils, GSit, ProtectItemFrame, Vault, eBackup, dynmap, WorldEdit, MiaoChat, EpicRename, WorldBorder, Multiverse-Core, Images, PWarp, DeluxeMenus, GiftPack, DeluxeHub, Essentials, WBAutoFill, HomeGUI, EssentialsProtect, EssentialsSpawn, BungeeTabListPlus

**Comment by WiIIiam278** [comment]
Hello, thanks for the report. Please can you provide me with the following:
- What command is failing to TAB complete?
- Describe what happens when you run the EssentialsX migrator
- Provide any error logs that appear in console when something does not work

**Comment by SnivyJ** [comment]
Tab can't finish with the exception of command
example I want use /tpa username to tp other player，but Tab cant completion username
and /home <HomeName> cant completion home name

When I ues /huskhomes migrate essentialsX
the console crash https://paste.ubuntu.com/p/j9RV5ZWNDC/

**Comment by WiIIiam278** [comment]
I've discovered a compatability issue with newer versions of EssentialsX when trying to migrate and have made some changes for 2.7 that might resolve the issue.￼ The new build will be available on the project discord for testing soon.

Are you migrating to a fresh HuskHomes database? The migrator currently only works when migrating fresh to a new database. Install HuskHomes and then 

Tab completion not working is strange. Are there any console errors when running that? It might be because of the failed migration that it's not working

**Comment by WiIIiam278** [comment]
Hello there @SnivyJ ,
Could you try the preview build HuskHomes 2.7-dev4 (https://github.com/WiIIiam278/HuskHomes2/releases/tag/2.7-dev4) and let me know if you still experience this issue? Please follow the following steps when migrating from Essentials to HuskHomes:

1. Stop your server
2. In your plugins folder, replace the old HuskHomes jar with the new one (https://github.com/WiIIiam278/HuskHomes2/releases/tag/2.7-dev4).
3. Open the "HuskHomes" folder in your plugins folder.
4. Rename the `HuskHomesData.db` file to something else, such as `HuskHomesDataBackup.db`. This is because Essentials migration works best with a blank database
5. Start your server. Once it has started, don't login yet
6. Run the command in console `huskhomes migrate essentialsx`
7. Wait for the migrator to migrate your homes. Let me know if there are still errors.

**Comment by SnivyJ** [comment]
HuskHomes 2.7-dev4 can import the home data of essentialsx normally 
Tab available
